name       : brogue
version    : 1.10.1
release    : 5
source     :
    - https://github.com/tmewett/BrogueCE/archive/refs/tags/v1.10.1.tar.gz : 3e0425b3f1b59afe98a92c0282aa4dd7e8964b53f7cab969fcf437701a04c5fa
homepage   : https://sites.google.com/site/broguegame/
license    :
    - AGPL-1.0-or-later
    - CC-BY-SA-4.0
component  : games.rpg
summary    : Brogue is a Roguelike game by Brian Walker (community edition)
description: |
    Brogue is a Roguelike game by Brian Walker. It is a direct descendant of Rogue, unlike other popular modern roguelikes, and it favors simplicity over complexity, while trying to ensure that the interactions  between components will be interesting and varied. It is possible to play entirely with the keyboard, or entirely with the mouse, or a combination of the two as the player chooses.
builddeps  :
    - pkgconfig(SDL2_image)
setup      : |
    %patch -p1 < $pkgfiles/0001-use-system-data-dir.patch
build      : |
    %make
install    : |
    install -Dm00755 bin/brogue $installdir/usr/bin/brogue
    install -Dm00644 $pkgfiles/brogue.desktop $installdir/usr/share/applications/brogue.desktop
    install -Dm00644 bin/assets/tiles* -t $installdir/usr/share/brogue/assets/
    install -Dm00644 bin/assets/icon.png $installdir/usr/share/brogue/assets/icon.png
    install -Dm00644 bin/assets/icon.png $installdir/usr/share/pixmaps/brogue.png
