name        : brogue
version     : 1.7.4
release     : 1
source      :
    - https://sites.google.com/site/broguegame/brogue-1.7.4-linux-amd64.tbz2 : eba5f35fe317efad9c97876f117eaf7a26956c435fdd2bc1a5989f0a4f70cfd3
license     : AGPL-1.0
component   : games.rpg
summary     : Brogue is a Roguelike game for Mac OS X, Windows and Linux
description :
    Brogue is a Roguelike game for Mac OS X, Windows and Linux by Brian Walker. It is a direct descendant of Rogue, unlike other popular modern roguelikes, and it favors simplicity over complexity, while trying to ensure that the interactions between components will be interesting and varied. It can be played on Mac OS X, Windows, or Linux, and it is possible to play entirely with the keyboard or entirely with the mouse or a combination of the two as the player chooses.
builddeps   :
    - pkgconfig(sdl)
    - libtcod-devel
    - desktop-file-utils
setup       : |
    %apply_patches
build       : |
    %make clean
    %make
install     : |
    install -Dm00755 bin/brogue $installdir/usr/bin/brogue
    install -dm00755 $installdir/usr/share/brogue/fonts
    install -Dm00644 bin/fonts/*.png $installdir/usr/share/brogue/fonts
    install -Dm00644 bin/brogue-icon.png $installdir/usr/share/pixmaps/brogue-icon.png
    install -d $installdir/usr/share/applications
    desktop-file-install --dir=$installdir/usr/share/applications -m 00644 brogue.desktop
